# Generated by Django 6.0.4 on 2026-04-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="signature",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="signer_public_key",
            field=models.TextField(blank=True),
        ),
    ]
